name: modiryat_mali
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  animated_bottom_navigation_bar: ^1.3.3
  searchbar_animation: ^0.0.4
  persian_datetime_picker: ^2.4.0
  flutter_svg: ^2.0.16
  fl_chart: ^0.69.2
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  incompatible_package_checker: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.1.7
  hive_generator: ^1.1.2
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
